apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: serveridea
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-1
  postgresVersion: 15
  instances:
    - name: postgresdb
      replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "nascluster"
        resources:
          requests:
            storage: 1000Gi
  users:
    - name: postgres
      options: "SUPERUSER"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-1
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-retention-diff: "30"  # Ajouté pour la rétention des sauvegardes différentielles
        repo1-retention-incr: "30"
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1000Gi
      # schedules: # non prise en charge
      #   full: "0 12 * * 0"  # Chaque dimanche à midi
      #   diff: "0 12 * * 1-6"  # Tous les jours à midi, sauf le dimanche

  service:
    metadata:
      annotations:
        annotation1: "mdnodeport1"
      labels:
        label1: "32000"
    type: NodePort
    nodePort: 32000