apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: serveridea
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-1
  postgresVersion: 15
  instances:
    - name: postgresdb
      replicas: 2
      resources:
        limits:
          cpu: "0.5"
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        volumeName: pvc-5b8e8522-b390-4fa2-b305-a368ff07e93c
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            volumeName: pvc-da3e027f-359c-49fe-a442-ca842551b83a
            resources:
              requests:
                storage: 1Gi
  service:
    metadata:
      annotations:
        annotation1: "mdnodeport1"
      labels:
        label1: "32000"
    type: NodePort
    nodePort: 32000