apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: serveridea
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-1
  postgresVersion: 15
  instances:
    - name: postgresdb
      replicas: 2
      resources:
        limits:
          cpu: "0.5"
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 200Gi
  users:
    - name: postgres
      options: "SUPERUSER"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-1
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 200Gi
      # schedules:
      #   full: "50 15 * * *"
  service:
    metadata:
      annotations:
        annotation1: "mdnodeport1"
      labels:
        label1: "32000"
    type: NodePort
    nodePort: 32000